### ISSUE TITLE
alternative to Auth0Lock._setOpenWindowFn?

### ISSUE THREAD

**Issue by at0g** [auth0/auth0-electron#12]
Where does `Auth0Lock._setOpenWindowFn` in the example come from exactly? Given that it's an electron project, wouldn't it be better to `require` auth0-lock rather than rely on a script tag in the html file?

Is `_setOpenWindowFn` an undocumented internal method that (may be)/(has been) removed?
The recommended version of auth0-lock according to their npm page is 10.x... If I change the auth0-lock script src in this project to `https://cdn.auth0.com/js/lock/10.0.0/lock.min.js`, it throws a runtime error that `_setOpenWindowFn` is not a function :(

I'm not too keen on missing out on bug/security fixes (especially with an auth package) - so is there another/better way of using auth0 with electron?

**Comment by uotw** [comment]
did you ever find a solution to this error?

**Comment by at0g** [comment]
@uotw Nope - perhaps the original author will chime in?

**Comment by chenkie** [comment]
`_setOpenWindowFn` is a private method that has been removed at Lock v10. We'll be updating this sample with support for Lock 10 very soon :)

**Comment by chenkie** [comment]
Updated in this sample: https://github.com/auth0-samples/auth0-electron-samples/tree/master/00-Starter-Seed
