### ISSUE TITLE
auth0-electron.js not compatible with lock v10

### ISSUE THREAD

**Issue by Amialc** [auth0/auth0-electron#15]
![image](https://cloud.githubusercontent.com/assets/1114365/17517094/761d6f30-5e4a-11e6-991c-ca583101f4f4.png)

**Comment by at0g** [comment]
Duplicate of #12

**Comment by AlexanderKozhevin** [comment]
:thumbsup:

**Comment by chenkie** [comment]
Updated to Lock 10.2 in this sample: https://github.com/auth0-samples/auth0-electron-samples/tree/master/00-Starter-Seed

**Comment by AlexanderKozhevin** [comment]
It's still not compatible when it works with electron using version 10.2.
I specified allowed urls like in example
```
https://polymath.auth0.com/mobile, file:///
```
And I got redirected to some page which throw an error.
![auth0error2](https://cloud.githubusercontent.com/assets/4464561/18037149/dadc6166-6d85-11e6-9857-f4fb38bce53a.JPG)

**Comment by chenkie** [comment]
Are you working from the sample or are you adapting your own project from it? If you are working in your own project, are you able to share your code?

**Comment by AlexanderKozhevin** [comment]
Oh, yeah. It's good with the latest version. Sorry.

**Comment by chenkie** [comment]
np :)
