### ISSUE TITLE
Sign up empty popup is frozen.

### ISSUE THREAD

**Issue by AlexanderKozhevin** [auth0/auth0-electron#16]
I downloaded latest example. 
There is an issue during registration. After confirm an empty popup window is shown. 
And it just do nothing. And it's not closed automatically.  And the progress circle is rotating infinitely. 
I got a confirmation email and I can login if I close that window by myself. But it's not cool in terms of UX and looks like it's broken. 
![screen shot 2016-09-12 at 12 21 59](https://cloud.githubusercontent.com/assets/4464561/18431063/f39523aa-78e3-11e6-83b8-2dfee1c2f717.png)

**Comment by AlexanderKozhevin** [comment]
And, btw. 
When an email is wrong  - already exist or some other error - the popup got hidden.

**Comment by AlexanderKozhevin** [comment]
@chenkie Is there a way to fix it rather then hacking _lock.js_?

**Comment by AlexanderKozhevin** [comment]
@chenkie If you need any assistance  I would be glad to help you.
skype: live:kozhevin
hangouts: turboasm21@gmail.com

**Comment by chenkie** [comment]
@AlexanderKozhevin moving this issue over to github.com/auth0/lock

Also, we've moved locations for our sample projects so I'm going to deprecate this one. The new location is here: https://github.com/auth0-samples/auth0-electron-samples
