### ISSUE TITLE
Callback URL error

### ISSUE THREAD

**Issue by golinmarq** [auth0/auth0-electron#17]
I'm using React as front end and auth electron. I have a problem after login. My callback URL  is localhost/login. Once I logged in I get a message that says CAN NOT GET /login

**Comment by chenkie** [comment]
For Electron apps you should use popup mode instead of redirect. Can you have a look at the [Electron sample](https://github.com/auth0-samples/auth0-electron-samples)? If there continues to be an issue, please open it there as this repo is deprecated.

**Comment by golinmarq** [comment]
@chenkie thanks! I made that but browserHistory.replace('/home') is not firing up

**Comment by b4dnewz** [comment]
@golinmarq did you solved it?

**Comment by golinmarq** [comment]
Sorry @b4newz I didn't. I change the login strategy and use another service =(
