### ISSUE TITLE
The login is not successful at all

### ISSUE THREAD

**Issue by golinmarq** [auth0/auth0-electron#7]
I'm testing the app with my variables but I had an issue when I clicked login. 
After I putted my username and password, it openned a Windows that says "Login was successful. Please close this tab to continue." but when I closed it, the lock sent me an error.

**Comment by chenkie** [comment]
Are you getting any errors in the console? I just tried it and wasn't able to reproduce the error.

Are you bringing in `auth0-electron.js`?

**Comment by golinmarq** [comment]
I got this error in the console: 
`Something went wrong:  Error: server error(…)
(anonymous function) @ index.html:33
(anonymous function) @ lock-8.2.min.js:4
(anonymous function) @ lock-8.2.min.js:8
(anonymous function) @ lock-8.2.min.js:9`

**Comment by chenkie** [comment]
Are you logging in with email/password or social? :)

**Comment by golinmarq** [comment]
I'm logging using my an username and password from my auth0 database connection

**Comment by chenkie** [comment]
Do you have a fork of the repo? I can take a look at that if you like.

**Comment by golinmarq** [comment]
Sure, thanks!

**Comment by chenkie** [comment]
Have you supplied your Auth0 client ID and your Auth0 domain to your Lock instance? https://github.com/golinmarq/auth0-electron/blob/master/index.html#L26

**Comment by golinmarq** [comment]
Yes, I put the auth0-variables.js with my own values

**Comment by golinmarq** [comment]
The login is successful, I can see it in the log of my dashboard. But the problem happens when I close the windows that says "Login was successful. Please close this tab to continue"

**Comment by chenkie** [comment]
Ah I just realized I forgot to include instructions in the readme for this repo on setting your allowed callback URLs. I just updated it now. Can you set the following in your Auth0 dashboard in the **Allowed Callback URLs** spot?

```
https://{your-domain}.auth0.com/mobile, file:///
```

**Comment by golinmarq** [comment]
Yes, that's done, but I'm geting ther error

**Comment by chenkie** [comment]
can you create a test user in your account for me to try with?

**Comment by golinmarq** [comment]
Sure. Your username is chenkie and password 123456789

**Comment by chenkie** [comment]
The error is showing that `file://` is an invalid origin. Can you show me what you have in your allowed callback URLs?

**Comment by golinmarq** [comment]
![allowedcallback](https://cloud.githubusercontent.com/assets/13850842/13299646/3d6353c2-db0e-11e5-9017-7801e5635885.png)

**Comment by chenkie** [comment]
Hmm. Should be working. Can you try putting `file:///` in the allowed origins instead?

**Comment by golinmarq** [comment]
It shows a new window with the word OK in it, but in the console there's an error `Uncaught TypeError: win.isDestroyed is not a function`. 
When a close this "OK window" the error appears again, but now says `Something went wrong:  Error: Browser window closed(…)`. 
I'd checked my Local Storage and there's not any token

**Comment by chenkie** [comment]
We just took a look at your account and it looks like you've got two apps in there. Can you make sure the allowed origins are set in the correct app? :)

**Comment by golinmarq** [comment]
Sure, I verified this. I spent the night checking the error, make an electron upgrade and it works. Thanks!

**Comment by chenkie** [comment]
Awesome, thanks!

**Comment by Toosick** [comment]
I can't seem to get `file:///` to work with our Electron app. I was able to get things working by adding the full callback `file:///` url into the `Allowed Callback URLs` setting. The callbacks work just fine on the web using the callback with `https://*.netlify.com/login`.

Client ID: QR579kSOEqhOqPAfqjfTPHaz5hJPvEKT

### Callback mismatch
![Callback mismatch](https://image.prntscr.com/image/oWZ5OXuXQxaVU20Ugck_yQ.png "Callback mismatch")

### Auth0 lock setup
![Auth0 lock setup](https://image.prntscr.com/image/up0m50tWRxyuLXOfTaC00w.png "Auth0 lock setup")
